pipeline:
  - name: Markdown
    sources:
      - _posts/*.md
    dictionary:
      language: en_US
    exclude:
      wordlist: .wordlist.txt
    filters:
      - pyspelling.filters.markdown:
          code_language: true
          header: true
          html: true
