name: Markdown Linting and Formatting
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint '**/*.md'
        
      - name: Install Prettier
        run: npm install -g prettier

      - name: Format Markdown files
        run: prettier --write '**/*.md'
