name: Jekyll GH-Pages Tagging Workflow

on:
    # Trigger when Markdown files pushed to docs/_posts on the master branch 
    push:
        branches:
            - main
        paths:
            - '_posts/*.md'
    workflow_dispatch:

jobs:
    generate_tags:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Generate Tags
              uses: ragdata/jekyll-ghpages-tagging@master
              with:
                posts_dir: "_posts"
                tags_dir: "_tags"
                tags_layout: "tags"
                feeds_dir: "_feeds"
                feeds_layout: "feed"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
