---
name: YAML Lint

"on":
  pull_request:
    branches:
      - main
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/**'

jobs:
  yaml-lint:
    name: 📝 Lint YAML Files
    runs-on: ubuntu-24.04

    steps:
      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v6

      - name: 📝 Run YAML Linter
        id: yaml-lint
        uses: ibiqlik/action-yamllint@v3

      - name: 📤 Upload Linting Errors
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: yamllint-errors
          path: ${{ steps.yaml-lint.outputs.logfile }}
          retention-days: 7
